export enum ErrorCode{
    // AUTH
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
    INVALID_CODE = 'INVALID_CODE',
    INVALID_OR_EXPIRED_CODE = 'INVALID_OR_EXPIRED_CODE',
    SEND_EMAIL_CODE_ERROR = 'SEND_EMAIL_CODE_ERROR',
    SENDING_EMAIL_LIMIT = 'SENDING_EMAIL_LIMIT',
    TIME_OUT_REGISTER = 'TIME_OUT_REGISTER',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    INVALID_TOKEN = 'INVALID_TOKEN',
    TOKEN_EXPIRED = 'TOKEN_EXPIRED',

    // USER

    // SYSTEM
    REDIS_SAVE_ERROR = 'REDIS_SAVE_ERROR',
    USER_CREATION_FAILED = 'USER_CREATION_FAILED',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    INTERNAL_HASH_ERROR = 'INTERNAL_HASH_ERROR',
    RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED'
}