export enum ErrorCode{
    // AUTH
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
    INVALID_CODE = 'INVALID_CODE',
    EXPIRED_CODE = 'INVALID_OR_EXPIRED_CODE',
    SEND_EMAIL_CODE_ERROR = 'SEND_EMAIL_CODE_ERROR',
    LIMIT_ATTEMPTS = 'LIMIT_ATTEMPTS',
    TIME_OUT_REGISTER = 'TIME_OUT_REGISTER',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    INVALID_TOKEN = 'INVALID_TOKEN',
    TOKEN_EXPIRED = 'TOKEN_EXPIRED',
    UNAUTHORIZED_USER = 'UNAUTHORIZED_USER',

    // DATABASE
    CREATE_DATABASE_ERROR = 'DATABASE_ERROR',
    UPDATE_DATABASE_ERROR = 'UPDATE_DATABASE_ERROR',
    QUERY_DATABASE_ERROR = 'QUERY_DATABASE_ERROR',
    DELETE_DATABASE_ERROR = 'DELETE_DATABASE_ERROR',

    // USER

    // SYSTEM
    REDIS_SAVE_ERROR = 'REDIS_SAVE_ERROR',
    REDIS_GET_ERROR = 'REDIS_GET_ERROR',
    USER_CREATION_FAILED = 'USER_CREATION_FAILED',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    INTERNAL_HASH_ERROR = 'INTERNAL_HASH_ERROR',
    RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED'
}