services:
  api:
    image: ghcr.io/SEU_USUARIO/orcafacil-api:latest
    container_name: orcafacil-api
    
    restart: unless-stopepd

    env_file:
      - .env.prod

    ports:
      - "3000:3000"

    depends_on:
      postgres:
        condition: service-healthy
      redis:
        condition: service_started

  postgres:
    image: postgres:17
    container_name: orcafacil-postgres

    restart: unless-stopped

    env_file:
      - .env.prod

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:8-alpine
    container_name: orcafacil-redis

    restart: unless-stopped

    volumes:
      - redis_data:/data

volumes:
  postgres-data:
  redis-data: